[package]
name = "server"
version = "0.1.0"
authors = ["Paul Weaver <paul@concertdaw.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }
tokio = { version = "1.2", features = ["macros", "rt-multi-thread"] }
websocket = {version = "0.26", features = ["async"] }
